# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 594e9498ee6cb396b71937df20a5167fa49eab845f0436b8236d437df5e3779eebe4ec01b2c7b0e26ce614505472ba6e9fdefa7e41f2724af895f28a23b6eacc

test:
  secret_key_base: b2e333eeb9b9f0ea109221b26861c4fb0ba9bad8a4209651fb25127ee2efe3e67f8803bd824d0afc03217567a47233d94495fb2a4d7c17a909ff09ea73e0ab33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
